# // GAME SETTINGS // #
RAND_SEED = None

STARTER_INNINGS_LIMIT = 5
STARTER_PITCHES_LIMIT = 95
STARTER_RUNS_LIMIT = 5
STARTER_HITS_LIMIT = 8
STARTER_STRUGGLE_LIMIT = 4.3

EXTENDED_STARTER_INNINGS_LIMIT = 7
EXTENDED_STARTER_PITCHES_LIMIT = 110
EXTENDED_STARTER_RUNS_LIMIT = 5
EXTENDED_STARTER_HITS_LIMIT = 10

RELIEVER_INNINGS_LIMIT = 2
RELIEVER_PITCHES_LIMIT = 25
RELIEVER_RUNS_LIMIT = 2
RELIEVER_HITS_LIMIT = 4

EXTENDED_RELIEVER_INNINGS_LIMIT = 3
EXTENDED_RELIEVER_PITCHES_LIMIT = 40
EXTENDED_RELIEVER_RUNS_LIMIT = 3
EXTENDED_RELIEVER_HITS_LIMIT = 5

INNINGS = 9
OUTS = 3
PICKOFFS = 2
